<?php

/**
 *
 * Multisite module for Processwire
 * Inspired by Multisite module made by authors: Ryan, Antti Peisa, Avoine Oy, Philipp "Soma" Urlich
 *
 * complete rewrite of the original and forked modules
 *
 * @author Christoph Thelen aka @kixe 2017/03/25
 * @copyright © 2017 Christoph Thelen
 * @license Licensed under MIT, see LICENSE.txt
 * @link https://processwire.com/talk/topic/...
 * @version 1.0.3
 * @since 1.0.0 init - 2017/05/09
 * @since 1.0.1 default rootpage, domain related access control for MultisitePageTree, fixed path bug - 2017/05/10
 * @since 1.0.2 fixed root page path issue in single language mode FORCE $page->template->slashUrls for rootPage - 2017/05/10
 * @since 1.0.3 fixed issue other language rootPageName, let hook modify Page view urls in admin too, take in account slashUrl and useHomeSegment settings - 2017/05/13
 * @todo modify page view links in admin (if accessed from non superuser and multisite domain)
 *
 * FEATURES
 * - multilanguage support
 * - domain related homepage and custom 404 is set by id
 * - no restriction about naming, even multilanguage
 * - path modification is done by hooks
 * - domain related access control of MultiSiteTree (shows 404 if doesn't match)
 *
 * REQUIREMENTS
 * root page of any MultisitePageTree must be a child of original root page e.g. $page->get(1)
 *
 * SETTINGS
 * in config.php
 * $config->MultisiteDomains = array(
 *		"example.com" => array( // domain name is used to map to root page allow subdomains
 *       	"root" => 1026, // page id of the root page
 *			"http404" => 27 // page id of custom 404 error page (optionally)
 *      ),
 * );
 *
 *
 * $config->httpHosts = array_unique(array_merge($config->httpHosts, array_keys($config->MultisiteDomains)));
 */

class Multisite extends WireData implements Module {

	public $domains = null; // settings array $config->MultisiteDomains
	public $domain = null; // $config->httpHost
	public $it = false; // sanitized $_GET['it'] if set

	public $page = null;
	public $rootPage = null; // page instance of root page related to domain
	public $rootPageID = 1; // page id of root page related to domain
	public $rootPageName = ''; // language sensitive page name of root page related to domain

	public $languageSupport = false;
	public $isAdmin = false;

	public static function getModuleInfo() {
		return array(
			'title' => 'Multisite',
			'version' => 103,
			'summary' => 'Allows multiple sites with different domains run from single PW-site and database.',
			'href' => 'https://github.com/kixe/Multisite',
			'singular' => true,
			'autoload' => true
			);
	}

	public function __construct() {
		// read config settings
		if(!empty($this->wire("config")->MultisiteDomains)) $this->domains = $this->wire("config")->MultisiteDomains;
		if (array_key_exists($this->wire('config')->httpHost, $this->domains)) {
			$this->domain = $this->wire('config')->httpHost;
			if (!array_key_exists('root', $this->domains[$this->domain])) throw new WireException("\$config->MultisiteDomains[$this->domain]['root'] not set");
			$this->rootPageID = $this->domains[$this->domain]['root'];
			
			$this->addHookAfter('AdminRestrictBranch::getBranchRootParentId', function($e) {
				// ATTENTION: make hooked function protected and hookable first
				$e->return = $this->rootPageID;
			});
				
		}
	}

	public function init() {
		// quick exit
		if(empty($this->domains) || $this->domain == null) return;

		// settings ok?
		$this->configCheck($this->domain);

		// set custom http 404 page
		if (isset($this->domains[$this->domain]['http404'])) $this->wire("config")->http404PageID = (int) $this->domains[$this->domain]['http404'];

		$superRootURL = $this->wire('config')->urls->root; // could be '/' or '/subfolder/'

		// dirty $_GET['it']
		if (isset($_GET['it'])) $this->it = $this->wire('sanitizer')->path($_GET['it']);

		// if in admin set flag
		if(strpos($superRootURL . $this->it, $this->wire('config')->urls->admin) === 0) $this->isAdmin = true;

		// if it's an assets file exit
		if(strpos($superRootURL . $this->it, $this->wire('config')->urls->assets) === 0) return;

		// if it's form-builder exit
		if(strpos($superRootURL . $this->it, "/form-builder/") !== false) return;

		// if called from PW front-end editing exit
		if($this->wire("input")->post->action == "PageFrontEditSave") return;

		// language support?
		if ($this->wire('modules')->isInstalled('LanguageSupportPageNames')) $this->languageSupport = true;

		// get root page instance
		$this->rootPage = $this->wire('pages')->get($this->rootPageID);
		$this->rootPageName = $this->rootPage->name;
		$this->page = $this->wire('pages')->get("path=/".trim($this->it,'/').'/');
		if (!$this->page->id) $this->page = $this->rootPage;
		$slash = $this->page->template->slashUrls? '/' : '';

		// redirect if $_GET['it'] doesn't match template->slashUrls settings
		if ($this->it && $this->isAdmin === false) {
			if ($this->page->template->slashUrls == 1 && substr($this->it, -1) != '/') $this->wire('session')->redirect("/$this->it/");
			if ($this->page->template->slashUrls == 0 && substr($this->it, -1) == '/')  $this->wire('session')->redirect("/".rtrim($this->it,'/'));
		}

		// modify $_GET['it']
		// multi language
		if ($this->languageSupport) {
			if ($this->it) {
				$it = explode('/',$this->it);
				$lid = $this->getLanguageIdByPageName($this->wire('pages')->get(1), $it[0]);
				$this->rootPageName = $this->rootPage->get("name$lid|name");
				array_splice($it, 1, 0, $this->rootPageName); // splice in at position 1
				$it = implode('/',$it);
			}
			else { // is homepage
				$lang = $this->wire('pages')->get(1)->name.'/';
				$it = "$lang$this->rootPageName$slash";
				if ($this->wire('modules')->get('LanguageSupportPageNames')->useHomeSegment) $this->wire('session')->redirect("$this->rootPageName$slash");
			}
		}
		// single language
		else $it = $this->it? "$this->rootPageName/$this->it" : "$this->rootPageName$slash"; // just prepend

		// add path hook
		$this->addHookBefore('Page::render', $this, 'hookPageRender');

		// set $_GET['it']
		if ($this->isAdmin === false) $_GET['it'] = $it;
	}

	/**
	 * Disallow access of pages residing in a MultisitePageTree for other domains other than the corresponding root page
	 *
	 */
	public function ready() {
		if ($this->wire('user')->isSuperuser()) return;
		$pageTreeIDs = $this->wire('page')->parents()->each('id');
		$pageTreeIDs[] = $this->wire('page')->id;
		$multisiteRootIDs = array_map(function($i) { return $i = $i['root']; }, $this->domains);
		$matches = array_intersect($multisiteRootIDs, $pageTreeIDs);
		if (empty($matches)) return;
		reset($matches);
		if (key($matches) == $this->wire('config')->httpHost) return;
		$view = new ProcessPageView();	
		$view->pageNotFound($this->wire('page'), $this->it, true, 'access not allowed');
	}

	/**
	 * Get language by page name
	 * @param  $page Page object
	 * @param  $name string
	 * @return bool/int language->id
	 *
	 */
	public function getLanguageIdByPageName(Page $page, $name) {
		if(!$this->modules->isInstalled("LanguageSupportPageNames")) return false;
		foreach($this->wire('languages') as $language) {
			$pageName = $page->get("name$language->id|name");
			if ($pageName == $name) return $language->id;
		}
		return false;
	}

	/**
	 * Hook Page::render hooks Page::path and LanguageSupportPageNames::getPagePath
	 *
	 * @param  HookEvent $e
	 * @see hookPagePath()
	 * @todo make hookable LanguageSupportPageNames::getPagePath
	 */
	protected function hookPageRender(HookEvent $e) {
		if ($this->languageSupport) $this->addHookAfter('LanguageSupportPageNames::getPagePath', $this, 'hookPagePath');
		else $this->addHookAfter('Page::path', $this, 'hookPagePath');
	}

	/**
	 * Hook is called from hookPageRender()
	 * modifies $page->url, $page->httpUrl, $page->path, $page->localPath() $page->localUrl(), $page->localHttpUrl()
	 * modifies page view urls ProcessPageListActions::getActions ProcessPageEdit::buildFormView
	 * @param  HookEvent $e
	 * @see hookPageRender()
	 */
	protected function hookPagePath(HookEvent $e) {
		// call from LanguageSupportPageNames
		if (isset($e->arguments[1])) {
			$lid = $e->arguments[1]->id;
			$this->langSegment = $this->wire('pages')->get(1)->get("name$lid|name").'/';
			$this->rootPageName = $this->rootPage->get("name$lid|name");
		} 
		if ($this->languageSupport
		&& $this->wire('modules')->get('LanguageSupportPageNames')->useHomeSegment == 0
		&& $this->wire('user')->language->isDefault()
		&& $e->object == $this->rootPage) {
			$e->return = '/';
		}
		else {
			if (strpos($e->return, $this->rootPageName) !== strlen($this->langSegment) + 1) return;
			$cut = strlen($this->langSegment) + strlen($this->rootPageName) + 2;
			$e->return = '/'.$this->langSegment.substr($e->return, $cut);
		}
	}

	/**
	 * check config settings
	 * @param  string $domain
	 * @throws Exception
	 */
	protected function configCheck($domain) {
		$ids = array('root' => $this->domains[$domain]['root']);
		if (array_key_exists('http404', $this->domains[$domain])) $ids['http404'] = $this->domains[$domain]['http404'];
		foreach ($ids as $key => $id) {
			$page = $this->wire('pages')->get($id);
			if ($page instanceof NullPage) throw new WireException(sprintf("The page with ID = %s doesn't exist. Check \$config->MultisiteDomains['$domain']['$key'].", $id));
		}
	}
}
